global.ERR_CONSTRUCTION_WILL_BE_PLACED_NEXT_TICK = -100;

global.REMOTE_REPAIRER_SPAWN_INTERVAL = 5000;

global.MINIMUM_HAUL_RESOURCE_AMOUNT = 450;
global.MINIMUM_HAUL_FROM_OUTPUT_LAB_RESOURCE_AMOUNT = 500;
global.MINIMUM_HAUL_CONTAINER_RESOURCE_AMOUNT = 700;

global.TERMINAL_MAX_ENERGY_STORAGE = 100000;
global.TERMINAL_MIN_ENERGY_STORAGE =  10000;
global.TERMINAL_MIN_ENERGY_STORAGE_FOR_HAULER_RETRIEVAL = 20000;

global.RESPAWN_TTL_NOT_YET_SET = 2.5;

global.WALLS_REPAIR_MAX = [];
global.WALLS_REPAIR_MAX[1] = 10000;
global.WALLS_REPAIR_MAX[2] = 60000;
global.WALLS_REPAIR_MAX[3] = 120000;
global.WALLS_REPAIR_MAX[4] = 300000;
global.WALLS_REPAIR_MAX[5] = 800000;
global.WALLS_REPAIR_MAX[6] = 1600000;
global.WALLS_REPAIR_MAX[7] = 3200000;
global.WALLS_REPAIR_MAX[8] = WALL_HITS_MAX;

global.BASE_MINERALS = [
    RESOURCE_ENERGY,
    RESOURCE_POWER,

    RESOURCE_HYDROGEN,
    RESOURCE_OXYGEN,
    RESOURCE_UTRIUM,
    RESOURCE_LEMERGIUM,
    RESOURCE_KEANIUM,
    RESOURCE_ZYNTHIUM,
    RESOURCE_CATALYST,
];