global.ERR_CONSTRUCTION_WILL_BE_PLACED_NEXT_TICK = -100;
global.ERR_NO_LAYOUT = -101;
global.ERR_REPAIR_RAMPARTS_FIRST = -102;

global.REMOTE_REPAIRER_SPAWN_INTERVAL = 5000;

// ------------------
// -- Haul Amounts --
// ------------------
global.RESOURCE_MINIMUM_HAUL_AMOUNT = 450;

global.LAB_OUTPUT_MINIMUM_HAUL_AMOUNT = 500;

global.CONTAINER_MINIMUM_HAUL_RESOURCE_AMOUNT = CONTAINER_CAPACITY - 1250;
global.CONTAINER_MINIMUM_ENERGY_STORAGE_FOR_WORKER_COLLECTION = CONTAINER_CAPACITY - 750;

global.TERMINAL_MAX_ENERGY_STORAGE = 100000;
global.TERMINAL_MIN_ENERGY_STORAGE =  10000;
global.TERMINAL_MIN_ENERGY_STORAGE_FOR_HAULER_RETRIEVAL = 20000;

global.RESPAWN_TTL_NOT_YET_SET = 2.5;

global.WALLS_REPAIR_MAX = [];
global.WALLS_REPAIR_MAX[1] = 10000;
global.WALLS_REPAIR_MAX[2] = 60000;
global.WALLS_REPAIR_MAX[3] = 120000;
global.WALLS_REPAIR_MAX[4] = 300000;
global.WALLS_REPAIR_MAX[5] = 800000;
global.WALLS_REPAIR_MAX[6] = 1600000;
global.WALLS_REPAIR_MAX[7] = 3200000;
global.WALLS_REPAIR_MAX[8] = WALL_HITS_MAX;

global.BASE_MINERALS = [
    RESOURCE_ENERGY,
    RESOURCE_POWER,

    RESOURCE_HYDROGEN,
    RESOURCE_OXYGEN,
    RESOURCE_UTRIUM,
    RESOURCE_LEMERGIUM,
    RESOURCE_KEANIUM,
    RESOURCE_ZYNTHIUM,
    RESOURCE_CATALYST,
];