const STORAGE_MAX_DEFAULT = 10000;
global.STORAGE_MAX = {};

STORAGE_MAX[RESOURCE_ENERGY]                        = 500000;
STORAGE_MAX[RESOURCE_POWER]                         = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_HYDROGEN]                      = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_OXYGEN]                        = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM]                        = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM]                       = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM]                     = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM]                      = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYST]                      = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM]                       = STORAGE_MAX_DEFAULT;

STORAGE_MAX[RESOURCE_HYDROXIDE]                     = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_KEANITE]              = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM_LEMERGITE]              = STORAGE_MAX_DEFAULT;

STORAGE_MAX[RESOURCE_UTRIUM_HYDRIDE]                = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM_OXIDE]                  = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_HYDRIDE]               = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_OXIDE]                 = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_HYDRIDE]             = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_OXIDE]               = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_HYDRIDE]              = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_OXIDE]                = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_HYDRIDE]               = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_OXIDE]                 = STORAGE_MAX_DEFAULT;

STORAGE_MAX[RESOURCE_UTRIUM_ACID]                   = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM_ALKALIDE]               = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_ACID]                  = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_ALKALIDE]              = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_ACID]                = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_ALKALIDE]            = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_ACID]                 = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_ALKALIDE]             = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_ACID]                  = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_ALKALIDE]              = STORAGE_MAX_DEFAULT;

STORAGE_MAX[RESOURCE_CATALYZED_UTRIUM_ACID]         = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_UTRIUM_ALKALIDE]     = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_KEANIUM_ACID]        = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_KEANIUM_ALKALIDE]    = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_LEMERGIUM_ACID]      = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]  = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_ZYNTHIUM_ACID]       = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]   = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_GHODIUM_ACID]        = STORAGE_MAX_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_GHODIUM_ALKALIDE]    = STORAGE_MAX_DEFAULT;
