const MINERAL_DEFAULT = 10000;
const T0_DEFAULT =      10000;
const T1_DEFAULT =      10000;
const T2_DEFAULT =       5000;
const T3_DEFAULT =      10000;

global.STORAGE_MAX = {};

STORAGE_MAX[RESOURCE_ENERGY]                        = 500000;
STORAGE_MAX[RESOURCE_POWER]                         =  10000;

// Minerals
STORAGE_MAX[RESOURCE_HYDROGEN]                      = MINERAL_DEFAULT;
STORAGE_MAX[RESOURCE_OXYGEN]                        = MINERAL_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM]                        = MINERAL_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM]                       = MINERAL_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM]                     = MINERAL_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM]                      = MINERAL_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYST]                      = MINERAL_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM]                       = MINERAL_DEFAULT;

// T0
STORAGE_MAX[RESOURCE_HYDROXIDE]                     = T0_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_KEANITE]              = T0_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM_LEMERGITE]              = T0_DEFAULT;

// T1
STORAGE_MAX[RESOURCE_UTRIUM_HYDRIDE]                = T1_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM_OXIDE]                  = T1_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_HYDRIDE]               = T1_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_OXIDE]                 = T1_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_HYDRIDE]             = T1_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_OXIDE]               = T1_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_HYDRIDE]              = T1_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_OXIDE]                = T1_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_HYDRIDE]               = T1_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_OXIDE]                 = T1_DEFAULT;

// T2
STORAGE_MAX[RESOURCE_UTRIUM_ACID]                   = T2_DEFAULT;
STORAGE_MAX[RESOURCE_UTRIUM_ALKALIDE]               = T2_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_ACID]                  = T2_DEFAULT;
STORAGE_MAX[RESOURCE_KEANIUM_ALKALIDE]              = T2_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_ACID]                = T2_DEFAULT;
STORAGE_MAX[RESOURCE_LEMERGIUM_ALKALIDE]            = T2_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_ACID]                 = T2_DEFAULT;
STORAGE_MAX[RESOURCE_ZYNTHIUM_ALKALIDE]             = T2_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_ACID]                  = T2_DEFAULT;
STORAGE_MAX[RESOURCE_GHODIUM_ALKALIDE]              = T2_DEFAULT;

// T3
STORAGE_MAX[RESOURCE_CATALYZED_UTRIUM_ACID]         = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_UTRIUM_ALKALIDE]     = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_KEANIUM_ACID]        = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_KEANIUM_ALKALIDE]    = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_LEMERGIUM_ACID]      = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]  = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_ZYNTHIUM_ACID]       = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]   = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_GHODIUM_ACID]        = T3_DEFAULT;
STORAGE_MAX[RESOURCE_CATALYZED_GHODIUM_ALKALIDE]    = T3_DEFAULT;
