const TERMINAL_MIN_STORE_DEFAULT = 3000;
const TERMINAL_MIN_STORE = {};
TERMINAL_MIN_STORE[RESOURCE_ENERGY]                        = 40000;
TERMINAL_MIN_STORE[RESOURCE_POWER]                         = 0;
TERMINAL_MIN_STORE[RESOURCE_HYDROGEN]                      = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_OXYGEN]                        = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_UTRIUM]                        = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_KEANIUM]                       = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_LEMERGIUM]                     = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_ZYNTHIUM]                      = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYST]                      = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_GHODIUM]                       = TERMINAL_MIN_STORE_DEFAULT;

TERMINAL_MIN_STORE[RESOURCE_HYDROXIDE]                     = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_ZYNTHIUM_KEANITE]              = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_UTRIUM_LEMERGITE]              = TERMINAL_MIN_STORE_DEFAULT;

TERMINAL_MIN_STORE[RESOURCE_UTRIUM_HYDRIDE]                = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_UTRIUM_OXIDE]                  = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_KEANIUM_HYDRIDE]               = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_KEANIUM_OXIDE]                 = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_LEMERGIUM_HYDRIDE]             = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_LEMERGIUM_OXIDE]               = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_ZYNTHIUM_HYDRIDE]              = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_ZYNTHIUM_OXIDE]                = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_GHODIUM_HYDRIDE]               = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_GHODIUM_OXIDE]                 = TERMINAL_MIN_STORE_DEFAULT;

TERMINAL_MIN_STORE[RESOURCE_UTRIUM_ACID]                   = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_UTRIUM_ALKALIDE]               = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_KEANIUM_ACID]                  = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_KEANIUM_ALKALIDE]              = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_LEMERGIUM_ACID]                = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_LEMERGIUM_ALKALIDE]            = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_ZYNTHIUM_ACID]                 = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_ZYNTHIUM_ALKALIDE]             = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_GHODIUM_ACID]                  = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_GHODIUM_ALKALIDE]              = TERMINAL_MIN_STORE_DEFAULT;

TERMINAL_MIN_STORE[RESOURCE_CATALYZED_UTRIUM_ACID]         = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_UTRIUM_ALKALIDE]     = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_KEANIUM_ACID]        = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_KEANIUM_ALKALIDE]    = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_LEMERGIUM_ACID]      = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]  = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_ZYNTHIUM_ACID]       = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]   = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_GHODIUM_ACID]        = TERMINAL_MIN_STORE_DEFAULT;
TERMINAL_MIN_STORE[RESOURCE_CATALYZED_GHODIUM_ALKALIDE]    = TERMINAL_MIN_STORE_DEFAULT;

const TERMINAL_MAX_STORE_DEFAULT = 4000;
const TERMINAL_MAX_STORE = {};
TERMINAL_MAX_STORE[RESOURCE_ENERGY]                        = 50000;
TERMINAL_MAX_STORE[RESOURCE_POWER]                         = 0;
TERMINAL_MAX_STORE[RESOURCE_HYDROGEN]                      = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_OXYGEN]                        = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_UTRIUM]                        = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_KEANIUM]                       = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_LEMERGIUM]                     = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_ZYNTHIUM]                      = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYST]                      = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_GHODIUM]                       = TERMINAL_MAX_STORE_DEFAULT;

TERMINAL_MAX_STORE[RESOURCE_HYDROXIDE]                     = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_ZYNTHIUM_KEANITE]              = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_UTRIUM_LEMERGITE]              = TERMINAL_MAX_STORE_DEFAULT;

TERMINAL_MAX_STORE[RESOURCE_UTRIUM_HYDRIDE]                = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_UTRIUM_OXIDE]                  = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_KEANIUM_HYDRIDE]               = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_KEANIUM_OXIDE]                 = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_LEMERGIUM_HYDRIDE]             = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_LEMERGIUM_OXIDE]               = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_ZYNTHIUM_HYDRIDE]              = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_ZYNTHIUM_OXIDE]                = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_GHODIUM_HYDRIDE]               = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_GHODIUM_OXIDE]                 = TERMINAL_MAX_STORE_DEFAULT;

TERMINAL_MAX_STORE[RESOURCE_UTRIUM_ACID]                   = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_UTRIUM_ALKALIDE]               = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_KEANIUM_ACID]                  = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_KEANIUM_ALKALIDE]              = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_LEMERGIUM_ACID]                = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_LEMERGIUM_ALKALIDE]            = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_ZYNTHIUM_ACID]                 = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_ZYNTHIUM_ALKALIDE]             = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_GHODIUM_ACID]                  = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_GHODIUM_ALKALIDE]              = TERMINAL_MAX_STORE_DEFAULT;

TERMINAL_MAX_STORE[RESOURCE_CATALYZED_UTRIUM_ACID]         = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_UTRIUM_ALKALIDE]     = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_KEANIUM_ACID]        = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_KEANIUM_ALKALIDE]    = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_LEMERGIUM_ACID]      = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]  = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_ZYNTHIUM_ACID]       = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]   = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_GHODIUM_ACID]        = TERMINAL_MAX_STORE_DEFAULT;
TERMINAL_MAX_STORE[RESOURCE_CATALYZED_GHODIUM_ALKALIDE]    = TERMINAL_MAX_STORE_DEFAULT;

// How much do we need to be above TERMINAL_MAX_STORE in order to sell?
const SELL_THRESHOLD_AMOUNT_DEFAULT = 35000;
const SELL_THRESHOLD_AMOUNT = {};
SELL_THRESHOLD_AMOUNT[RESOURCE_ENERGY]                        = 25000;
SELL_THRESHOLD_AMOUNT[RESOURCE_POWER]                         = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_HYDROGEN]                      = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_OXYGEN]                        = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_UTRIUM]                        = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_KEANIUM]                       = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_LEMERGIUM]                     = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_ZYNTHIUM]                      = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYST]                      = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_GHODIUM]                       = SELL_THRESHOLD_AMOUNT_DEFAULT;

SELL_THRESHOLD_AMOUNT[RESOURCE_HYDROXIDE]                     = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_ZYNTHIUM_KEANITE]              = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_UTRIUM_LEMERGITE]              = SELL_THRESHOLD_AMOUNT_DEFAULT;

SELL_THRESHOLD_AMOUNT[RESOURCE_UTRIUM_HYDRIDE]                = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_UTRIUM_OXIDE]                  = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_KEANIUM_HYDRIDE]               = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_KEANIUM_OXIDE]                 = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_LEMERGIUM_HYDRIDE]             = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_LEMERGIUM_OXIDE]               = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_ZYNTHIUM_HYDRIDE]              = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_ZYNTHIUM_OXIDE]                = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_GHODIUM_HYDRIDE]               = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_GHODIUM_OXIDE]                 = SELL_THRESHOLD_AMOUNT_DEFAULT;

SELL_THRESHOLD_AMOUNT[RESOURCE_UTRIUM_ACID]                   = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_UTRIUM_ALKALIDE]               = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_KEANIUM_ACID]                  = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_KEANIUM_ALKALIDE]              = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_LEMERGIUM_ACID]                = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_LEMERGIUM_ALKALIDE]            = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_ZYNTHIUM_ACID]                 = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_ZYNTHIUM_ALKALIDE]             = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_GHODIUM_ACID]                  = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_GHODIUM_ALKALIDE]              = SELL_THRESHOLD_AMOUNT_DEFAULT;

SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_UTRIUM_ACID]         = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_UTRIUM_ALKALIDE]     = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_KEANIUM_ACID]        = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_KEANIUM_ALKALIDE]    = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_LEMERGIUM_ACID]      = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]  = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_ZYNTHIUM_ACID]       = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]   = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_GHODIUM_ACID]        = SELL_THRESHOLD_AMOUNT_DEFAULT;
SELL_THRESHOLD_AMOUNT[RESOURCE_CATALYZED_GHODIUM_ALKALIDE]    = SELL_THRESHOLD_AMOUNT_DEFAULT;

const AUTOSELL_RESOURCES = [
    RESOURCE_ENERGY,
    RESOURCE_HYDROGEN,
    RESOURCE_OXYGEN,
    RESOURCE_UTRIUM,
    RESOURCE_KEANIUM,
    RESOURCE_LEMERGIUM,
    RESOURCE_ZYNTHIUM,
    RESOURCE_CATALYST,
];

module.exports = {
    TERMINAL_MIN_STORE: TERMINAL_MIN_STORE,
    TERMINAL_MAX_STORE: TERMINAL_MAX_STORE,
    SELL_THRESHOLD_AMOUNT: SELL_THRESHOLD_AMOUNT,
    AUTOSELL_RESOURCES: AUTOSELL_RESOURCES,
};