const MIN_STORAGE_DEFAULT = 3000;
const MIN_STORAGE = {};
MIN_STORAGE[RESOURCE_ENERGY]                        = 40000;
MIN_STORAGE[RESOURCE_POWER]                         = 0;
MIN_STORAGE[RESOURCE_HYDROGEN]                      = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_OXYGEN]                        = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_UTRIUM]                        = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_KEANIUM]                       = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_LEMERGIUM]                     = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_ZYNTHIUM]                      = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYST]                      = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_GHODIUM]                       = MIN_STORAGE_DEFAULT;

MIN_STORAGE[RESOURCE_HYDROXIDE]                     = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_ZYNTHIUM_KEANITE]              = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_UTRIUM_LEMERGITE]              = MIN_STORAGE_DEFAULT;

MIN_STORAGE[RESOURCE_UTRIUM_HYDRIDE]                = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_UTRIUM_OXIDE]                  = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_KEANIUM_HYDRIDE]               = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_KEANIUM_OXIDE]                 = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_LEMERGIUM_HYDRIDE]             = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_LEMERGIUM_OXIDE]               = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_ZYNTHIUM_HYDRIDE]              = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_ZYNTHIUM_OXIDE]                = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_GHODIUM_HYDRIDE]               = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_GHODIUM_OXIDE]                 = MIN_STORAGE_DEFAULT;

MIN_STORAGE[RESOURCE_UTRIUM_ACID]                   = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_UTRIUM_ALKALIDE]               = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_KEANIUM_ACID]                  = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_KEANIUM_ALKALIDE]              = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_LEMERGIUM_ACID]                = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_LEMERGIUM_ALKALIDE]            = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_ZYNTHIUM_ACID]                 = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_ZYNTHIUM_ALKALIDE]             = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_GHODIUM_ACID]                  = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_GHODIUM_ALKALIDE]              = MIN_STORAGE_DEFAULT;

MIN_STORAGE[RESOURCE_CATALYZED_UTRIUM_ACID]         = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_UTRIUM_ALKALIDE]     = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_KEANIUM_ACID]        = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_KEANIUM_ALKALIDE]    = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_LEMERGIUM_ACID]      = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]  = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_ZYNTHIUM_ACID]       = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]   = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_GHODIUM_ACID]        = MIN_STORAGE_DEFAULT;
MIN_STORAGE[RESOURCE_CATALYZED_GHODIUM_ALKALIDE]    = MIN_STORAGE_DEFAULT;

const MAX_STORAGE_DEFAULT = 4000;
const MAX_STORAGE = {};
MAX_STORAGE[RESOURCE_ENERGY]                        = 50000;
MAX_STORAGE[RESOURCE_POWER]                         = 0;
MAX_STORAGE[RESOURCE_HYDROGEN]                      = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_OXYGEN]                        = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_UTRIUM]                        = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_KEANIUM]                       = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_LEMERGIUM]                     = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_ZYNTHIUM]                      = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYST]                      = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_GHODIUM]                       = MAX_STORAGE_DEFAULT;

MAX_STORAGE[RESOURCE_HYDROXIDE]                     = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_ZYNTHIUM_KEANITE]              = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_UTRIUM_LEMERGITE]              = MAX_STORAGE_DEFAULT;

MAX_STORAGE[RESOURCE_UTRIUM_HYDRIDE]                = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_UTRIUM_OXIDE]                  = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_KEANIUM_HYDRIDE]               = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_KEANIUM_OXIDE]                 = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_LEMERGIUM_HYDRIDE]             = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_LEMERGIUM_OXIDE]               = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_ZYNTHIUM_HYDRIDE]              = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_ZYNTHIUM_OXIDE]                = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_GHODIUM_HYDRIDE]               = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_GHODIUM_OXIDE]                 = MAX_STORAGE_DEFAULT;

MAX_STORAGE[RESOURCE_UTRIUM_ACID]                   = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_UTRIUM_ALKALIDE]               = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_KEANIUM_ACID]                  = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_KEANIUM_ALKALIDE]              = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_LEMERGIUM_ACID]                = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_LEMERGIUM_ALKALIDE]            = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_ZYNTHIUM_ACID]                 = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_ZYNTHIUM_ALKALIDE]             = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_GHODIUM_ACID]                  = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_GHODIUM_ALKALIDE]              = MAX_STORAGE_DEFAULT;

MAX_STORAGE[RESOURCE_CATALYZED_UTRIUM_ACID]         = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_UTRIUM_ALKALIDE]     = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_KEANIUM_ACID]        = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_KEANIUM_ALKALIDE]    = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_LEMERGIUM_ACID]      = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]  = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_ZYNTHIUM_ACID]       = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]   = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_GHODIUM_ACID]        = MAX_STORAGE_DEFAULT;
MAX_STORAGE[RESOURCE_CATALYZED_GHODIUM_ALKALIDE]    = MAX_STORAGE_DEFAULT;

module.exports = {
    MIN_STORAGE: MIN_STORAGE,
    MAX_STORAGE: MAX_STORAGE,
};